services:
  solarmeter:
    image: solarmeter
    container_name: solarmeter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/solarmeter.conf:/etc/solarmeter.conf
    devices:
      - /dev/ttyUSB0
    # solarmeter:uucp
    user: 964:987
