{
 "title": "Solarmeter",
 "description": "Show data from a smart energy meter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  total_energy\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Energy Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', NOW()) as time,\n  last(total_energy, time) - first(total_energy, time) as energy_today\nFROM live\nWHERE\n  time > date_trunc('day', NOW())"
    }
   ]
  },
  {
   "title": "Grid Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT                                                   \n  time,\n  grid_power\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Daily Energy",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  energy\nFROM daily_view\nWHERE\n  $__timeFilter(time)\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT\n  time,\n  credit\nFROM daily_view\nWHERE\n  $__timeFilter(time)\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Average Credit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS time,\n  avg(credit)\nFROM monthly_view"
    }
   ]
  },
  {
   "title": "Current Credit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('month', NOW()) AS time,\n  sum(payment) AS credit \nFROM daily_view\nWHERE\n  time > date_trunc('month', NOW())"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  AVG(efficiency) OVER(ORDER BY time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Monthly Energy",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  energy\nFROM monthly_view\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time,\n  credit\nFROM monthly_view\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket_5m AS time,\n  power_5m AS power\nFROM cagg_power\nWHERE\n  $__timeFilter(bucket_5m)\nORDER BY 1"
    }
   ]
  }
 ]
}